services:
  - type: web
    name: tasktogether-api
    env: docker
    plan: free
    startCommand: ""
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
