services:
  - type: web
    name: tasktogether-api
    env: java
    plan: free
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/TaskTogether-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
